<div style="text-align: center; background-color: #f0f8ff; padding: 20px; border-radius: 10px;">
    <h1 style="color: #5a90e2;">Introduction to NumPy</h1>
    <h3 style="color: #433333;">A Python Personal Project</h3>
</div>

# <h1 style="color: #2e6c80;">Introduction to NumPy</h1>

NumPy is a powerful Python library widely used for numerical computations. It provides support for large, multi-dimensional arrays and matrices, along with a variety of mathematical functions to operate on these arrays efficiently. NumPy is at the core of almost all scientific computing in Python.

## Why Use NumPy?
1. **Efficiency**: NumPy arrays are more compact and faster than Python lists, making them the go-to tool for handling large datasets.
2. **Convenience**: NumPy comes with many built-in functions to perform operations like sorting, reshaping, or performing mathematical computations quickly.
3. **Interoperability**: Many libraries such as pandas, scikit-learn, and TensorFlow rely on NumPy arrays, so understanding it is fundamental to data science and machine learning workflows.

## Key Concepts of NumPy
### 1. Arrays (an array is a structure for storing and retrieving data.)
NumPy arrays are similar to Python lists, but they come with additional capabilities. NumPy arrays are homogeneous, meaning that all elements in an array are of the same type. Arrays can also be multi-dimensional.

## Differences between lists and NumPy Arrays
* An array's size is immutable.  You cannot append, insert or remove elements, like you can with a list.
* All of an array's elements must be of the same [data type](https://docs.scipy.org/doc/numpy-1.14.0/user/basics.types.html).
* A NumPy array behaves in a Pythonic fashion.  You can `len(my_array)` just like you would assume.

# <h2 style="color: #2e6c80;">Importing NumPy</h2>

<p>To use NumPy, you first need to import the <code>numpy</code> package:</p>

```python
import numpy as np


In [5]:
# Importing NumPy for efficient numerical operations
import numpy as np

# Creating a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print('1D Array:', arr_1d)


# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print('2D Array:\n', arr_2d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## Multidimensional Arrays
* The data structure is actually called `ndarray`, representing any **n**umber of **d**imensions
* Arrays can have multiple dimensions, you declare them on creation
* Dimensions help define what each element in the array represents.  A two dimensional array is just an array of arrays
* **Rank** defines how many dimensions an array contains 
* **Shape** defines the length of each of the array's dimensions
* Each dimension is also referred to as an **axis**, and they are zero-indexed. Multiples are called **axes**.
* A 2d array is AKA **matrix**.

In [7]:
# Create an array of ones
ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
students_gpas = np.array([
    [4.0, 3.286, 3.5, 4.0],
    [3.2, 3.8, 4.0, 4.0],
    [3.96, 3.92, 4.0, 4.0]
])
students_gpas

array([[4.   , 3.286, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]])

In [9]:
# Check the number of dimensions in the array
students_gpas.ndim


2

In [10]:
# Get the shape (dimensions) of the array
students_gpas.shape

(3, 4)

In [11]:
# Get the total number of elements in the array
students_gpas.size

12

In [12]:
# Get the number of rows in the array (top-level elements)
len(students_gpas)

3

In [13]:
# Get the size (in bytes) of one element in the array
students_gpas.itemsize

8

In [14]:
# Calculate the total memory used by the array (in bytes)
students_gpas.itemsize * students_gpas.size

96

In [15]:
# List all ndarray variables in the current environment with details
%whos ndarray

Variable        Type       Data/Info
------------------------------------
arr_1d          ndarray    5: 5 elems, type `int32`, 20 bytes
arr_2d          ndarray    2x3: 6 elems, type `int32`, 24 bytes
ones            ndarray    5x3: 15 elems, type `float64`, 120 bytes
students_gpas   ndarray    3x4: 12 elems, type `float64`, 96 bytes


### 2. Array Shape and Reshaping
The shape of a NumPy array refers to its dimensions. For example, a 2D array has two axes: rows and columns. You can check the shape of an array and reshape it if needed.



In [17]:
# Checking the shape of the 2D array
print('Shape of 2D Array:', arr_2d.shape) 

# Reshaping the array into a different shape
reshaped_arr = arr_2d.reshape(3, 2)
print('Reshaped Array:\n', reshaped_arr)


Shape of 2D Array: (2, 3)
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


## How to Convert a 1D Array into a 2D Array (Adding a New Axis to an Array)

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

- Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. 
  - For example, a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

### Example:

In [19]:
arr = np.array([1, 2, 3, 4])
print(arr.shape)  

(4,)


In [20]:
arr1= arr[np.newaxis, :]
arr1.shape

(1, 4)

In [21]:
arr2 = np.expand_dims(arr, axis=1)
arr2.shape

(4, 1)

### 3. Mathematical Operations
NumPy supports element-wise operations on arrays, making it simple to perform complex calculations across entire datasets.


In [23]:
# Basic Mathematical Operations
arr = np.array([1, 2, 3, 4, 5])

# Adding a scalar value to each element
print('Array + 5:', arr + 5)

# Element-wise multiplication
print('Array * 2:', arr * 2)

# Finding the mean of the array
print('Mean of array:', np.mean(arr))

# Element-wise subtraction
print('Array - 2:', arr - 2)

# Element-wise division
print('Array / 2:', arr / 2)

# Finding the sum of the array
print('Sum of array:', np.sum(arr))

# Finding the maximum value in the array
print('Max value in array:', np.max(arr))

# Finding the minimum value in the array
print('Min value in array:', np.min(arr))

# Calculating the standard deviation
print('Standard deviation of array:', np.std(arr))

# Element-wise exponentiation
print('Array squared:', arr ** 2)

# Element-wise square root
print('Square root of array:', np.sqrt(arr))


Array + 5: [ 6  7  8  9 10]
Array * 2: [ 2  4  6  8 10]
Mean of array: 3.0
Array - 2: [-1  0  1  2  3]
Array / 2: [0.5 1.  1.5 2.  2.5]
Sum of array: 15
Max value in array: 5
Min value in array: 1
Standard deviation of array: 1.4142135623730951
Array squared: [ 1  4  9 16 25]
Square root of array: [1.         1.41421356 1.73205081 2.         2.23606798]


### 4. Broadcasting
Broadcasting is a powerful feature in NumPy that allows operations on arrays of different shapes. NumPy automatically stretches the dimensions to perform the operation.



In [25]:
 arr_broad = np.array([1, 2, 3])
arr_2d_broad = np.array([[10], [20], [30]])

# Adding a 1D array to a 2D array
result_broad = arr_2d_broad + arr_broad
print('Broadcasting Result 1:\n', result_broad)

Broadcasting Result 1:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


In [26]:
arr_subtract = np.array([5, 10, 15])
arr_2d_subtract = np.array([[50], [100], [150]])

# Subtracting a 1D array from a 2D array
result_subtract = arr_2d_subtract - arr_subtract
print('Broadcasting Result 2:\n', result_subtract)

Broadcasting Result 2:
 [[ 45  40  35]
 [ 95  90  85]
 [145 140 135]]


In [27]:
arr_multiply = np.array([2, 3, 4])
arr_3d_multiply = np.array([[[1], [2]], [[3], [4]], [[5], [6]]])  # Shape (3, 2, 1)

# Multiplying a 1D array with a 3D array
result_multiply = arr_3d_multiply * arr_multiply
print('Broadcasting Result 3:\n', result_multiply)

Broadcasting Result 3:
 [[[ 2  3  4]
  [ 4  6  8]]

 [[ 6  9 12]
  [ 8 12 16]]

 [[10 15 20]
  [12 18 24]]]


In [28]:
arr_scalar = np.array([[10, 20, 30], [40, 50, 60]])
scalar_value = 5

# Adding a scalar value to each element in the 2D array
result_scalar = arr_scalar + scalar_value
print('Broadcasting Result 4:\n', result_scalar)

Broadcasting Result 4:
 [[15 25 35]
 [45 55 65]]


In [29]:
arr_broad_2d = np.array([1, 2, 3])         # Shape (3,)
arr_2d_broad_2d = np.array([[10, 20], [30, 40], [50, 60]])  # Shape (3, 2)

# Adding a 1D array to a 2D array
result_broad_2d = arr_2d_broad_2d + arr_broad_2d[:, np.newaxis]
print('Broadcasting Result 5:\n', result_broad_2d)

Broadcasting Result 5:
 [[11 21]
 [32 42]
 [53 63]]


### 5. Slicing and Indexing
You can access and modify parts of NumPy arrays through slicing and indexing, similar to Python lists.



In [31]:
import numpy as np

# 1D Array Example
arr3 = np.array([1, 8, 3, 4])

# Slicing a 1D array
slice_arr = arr3[1:4]  # Elements from index 1 to 3
print('Sliced Array:', slice_arr)  # Output: [8, 3, 4]

# Additional examples for 1D array slicing
print('First element:', arr3[0])          # Accessing the first element
print('Last element:', arr3[-1])          # Accessing the last element
print('Elements from index 1:', arr3[1:])  # Slicing from index 1 to the end
print('Elements up to index 2:', arr3[:3]) # Slicing from the start to index 2
print('Reversed Array:', arr3[::-1])      # Reversing the array

Sliced Array: [8 3 4]
First element: 1
Last element: 4
Elements from index 1: [8 3 4]
Elements up to index 2: [1 8 3]
Reversed Array: [4 3 8 1]


In [32]:
# 2D Array Example
arr_2d1 = np.array([[1, 2, 3], [4, 8, 5]])

# Indexing a 2D array
element = arr_2d1[1, 2]  # Accessing element at row 1, column 2
print('Element at (1, 2):', element)  # Output: 5

# Additional examples for 2D array indexing and slicing
print('Element at (0, 1):', arr_2d1[0, 1])  # Accessing element at row 0, column 1
print('First row:', arr_2d1[0])             # Accessing the first row
print('Second column:', arr_2d1[:, 1])      # Accessing the second column using slicing
print('All rows, last column:', arr_2d1[:, -1])  # Accessing all rows, last column
print('Slicing rows 0 to 1:', arr_2d1[0:2])  # Slicing rows 0 to 1 (inclusive)
print('Slicing the last row:', arr_2d1[-1:]) # Slicing the last row

# Slicing specific elements from a 2D array
sliced_elements = arr_2d1[0:2, 1:3]  # Slicing the first two rows and columns 1 to 2
print('Sliced elements (first two rows, columns 1 to 2):\n', sliced_elements)

Element at (1, 2): 5
Element at (0, 1): 2
First row: [1 2 3]
Second column: [2 8]
All rows, last column: [3 5]
Slicing rows 0 to 1: [[1 2 3]
 [4 8 5]]
Slicing the last row: [[4 8 5]]
Sliced elements (first two rows, columns 1 to 2):
 [[2 3]
 [8 5]]


## Conclusion

NumPy is a versatile and essential library for numerical computing. Its array structure, built-in mathematical functions, and support for broadcasting and efficient slicing make it ideal for handling large datasets in scientific computing, data analysis, and machine learning. Understanding NumPy is crucial for working effectively with other data science libraries.
