# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.
 

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10]) # or 
arr1 = np.arange(1,11)

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.
 

In [27]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.
 

In [46]:
arr2 = np.linspace(0,5,10)
print(arr2)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.



In [33]:
arr3 = np.identity(5)
print(arr3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.
 

In [48]:
arr4 = np.random.rand(4,4)
print(arr4)

[[0.19821348 0.87314535 0.87982823 0.78041216]
 [0.34616158 0.22058418 0.48611581 0.62560526]
 [0.43374694 0.43104267 0.0698116  0.36149968]
 [0.45077235 0.16681392 0.4179006  0.12279826]]


---

### Exercise 6:
Find the shape of a NumPy array.


In [53]:
arr4.shape

(4, 4)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [60]:
arr5 = np.arange(1,17)
arr5 = arr5.reshape(4,4)
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [77]:
arr5.dtype

dtype('int32')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.
 

In [80]:
arr6 = np.arange(1,101)
even_arr = arr6[arr6 % 2 == 0]
print(even_arr)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.
 

In [89]:
arr7 = np.random.randint(10,50, size =(6,6))
print(arr7)

[[21 11 22 38 29 29]
 [34 39 45 44 26 29]
 [12 34 28 48 29 16]
 [40 36 41 21 28 45]
 [36 37 37 16 38 30]
 [49 33 27 49 21 18]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.
 

In [96]:
arr8 = arr7[1:3,1:4]
print(arr8)

[[39 45 44]
 [34 28 48]]


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [101]:
sum_arr = np.sum(arr8)
print(sum_arr)

238


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.
 

In [107]:
mean_arr = np.mean(arr8)
print(mean_arr)
media_arr = np.median(arr8)
print(media_arr)
sd_arr = np.std(arr8)
print(sd_arr)

39.666666666666664
41.5
6.896053621859068


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [110]:
min_arr = np.min(arr8)
print("The minimum value is:",min_arr)
max_arr = np.max(arr8)
print("The maximum value is :",max_arr)

The minimum value is: 28
The maximum value is : 48


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [133]:
arr9 = np.random.randint(100,size = (20))
print(arr9)
max_ar = np.argmax(arr9)
print(max_ar)

[13 47 31 54 21 53 17 67 95  8 21 47 53 20 28 39  6 53 29 69]
8


---

### Exercise 16:
Create a NumPy array and reverse its elements.
 

In [145]:
arr10 = np.arange(10)
arr10 = arr10[::-1]
print(arr10)

[9 8 7 6 5 4 3 2 1 0]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.
 

In [161]:
arr11 = np.random.randint(10, size =(2,2))
arr12 = np.random.randint(10, size =(1,2))
mult_arr = np.multiply(arr11,arr12)
print(mult_arr)

[[ 0 21]
 [56  6]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.
 

In [154]:
arr13 = np.arange(5)
diago_arr = np.diag(arr13)
print(diago_arr)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [157]:
arr14 = np.random.randint(10,size = (3,2))
arr15 = np.random.randint(10,size = (2,3))
print(arr14@arr15)

[[38 70 12]
 [60 64  8]
 [11 31  6]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [166]:
arr16 = np.random.rand(2,3)
print(np.ndarray.flatten(arr16))

[0.39127167 0.91155008 0.80765461 0.608557   0.60526402 0.74521334]


---

### Exercise 21:
Stack two NumPy arrays vertically.
 

In [186]:
arra = np.arange(5)
arra1 = np.arange(5)
print(np.vstack((arra,arra1)))

[[0 1 2 3 4]
 [0 1 2 3 4]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

In [189]:
arra = np.arange(5)
arra1 = np.arange(5)
print(np.hstack((arra,arra1)))

[0 1 2 3 4 0 1 2 3 4]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.
 

In [194]:
arra3 = np.hstack((arra,arra1))
print(np.split(arra3,2))

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.
 

In [7]:
arr=np.random.rand(10)
rounded_arr=np.round(arr, 2)
print(rounded_arr)

[0.21 0.72 0.48 0.08 0.72 0.98 0.26 0.31 0.86 0.29]


---

### Exercise 25:
Find the unique elements of a NumPy array.
 

In [10]:
arr=np.array([2,3,4,5,7,1,2])
print(np.unique(arr))

[1 2 3 4 5 7]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.
 

In [13]:
arr1 = np.arange(6)
value = 3
arr1[arr1 < value] = value
print(arr1)

[3 3 3 3 4 5]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.
 

In [16]:
arr1 = np.arange(7)
np.cumsum(arr1)

array([ 0,  1,  3,  6, 10, 15, 21])

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [19]:
arr1 = np.random.randint(7)
np.count_nonzero(arr1)


1

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.
 

In [22]:
arra = np.random.randint(5, 20,10)
np.sort(arra)

array([ 5,  5,  5,  9, 11, 13, 15, 17, 18, 19])

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [25]:
arr = np.random.randint(4,9,size = (3,3))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=0))

[19 17 21]
[19 18 20]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).
 

In [28]:
arr= np.random.rand(2, 2) * 10
normalized_arr=(arr-np.max(arr))/(np.max(arr)-np.min(arr))
print(normalized_arr)

[[-0.46394737 -0.71791272]
 [-1.          0.        ]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---